from transformers import pipeline
import gradio as gr

# Load the text generation pipeline from Hugging Face
generator = pipeline('text-generation', model='gpt2')

def explain_rainbows():
    prompt = "Explain how rainbows are formed"
    results = generator(prompt, max_length=100, num_return_sequences=1)
    explanation = results[0]['generated_text']
    response = explanation.replace(prompt, '').strip()
    return response

css = """
#explain-button {
    background-color: #3498db;
    color: white;
    font-weight: 700;
    font-size: 1.2rem;
    padding: 15px 40px;
    border-radius: 12px;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s ease;
    margin-top: 1rem;
}
#explain-button:hover {
    background-color: #2980b9;
}
#output-box textarea {
    font-size: 1.1rem !important;
    font-weight: 600 !important;
    color: #2c3e50 !important;
    border: 2px solid #2980b9 !important;
    border-radius: 10px !important;
    padding: 10px !important;
    background-color: #ecf0f1 !important;
    resize: vertical !important;
}
"""

with gr.Blocks(css=css) as demo:
    gr.Markdown(
        """
        <h1 style="font-weight: 900; font-size: 3rem; color: #2c3e50; text-align:center;">
        🌈 How are Rainbows Formed?
        </h1>
        """
    )
    gr.Markdown(
        """
        <p style="font-size: 1.25rem; font-weight: 600; color: #34495e; text-align:center; margin-bottom: 2rem;">
        Click the button below to get a clear explanation generated by AI.
        </p>
        """
    )
    
    explanation_output = gr.Textbox(
        label="AI Explanation",
        lines=7,
        interactive=False,
        elem_id="output-box",
        max_lines=10
    )
    
    run_button = gr.Button(
        "Explain Rainbows",
        elem_id="explain-button"
    )
    
    run_button.click(fn=explain_rainbows, outputs=explanation_output)

demo.launch(inbrowser=True, share=False)
